version: '3'

services:
  app:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - FLASK_ENV=production
      - PORT=${PORT:-5000}
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ~/.ssh/github_code_challenge_setup:/root/.ssh/github_code_challenge_setup:ro
      - ~/.ssh/github_code_challenge_setup.pub:/root/.ssh/github_code_challenge_setup.pub:ro
    restart: unless-stopped

